PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX tbox: <http://www.softlang.org/ontologies/tbox#>
PREFIX ae: <http://www.softlang.org/ontologies/ae#>
PREFIX ce: <http://www.softlang.org/ontologies/ce#>
PREFIX fe: <http://www.softlang.org/ontologies/fe#>
PREFIX ie: <http://www.softlang.org/ontologies/ie#>
PREFIX le: <http://www.softlang.org/ontologies/le#>
PREFIX pe: <http://www.softlang.org/ontologies/pe#>
PREFIX te: <http://www.softlang.org/ontologies/te#>

CONSTRUCT {
  ?subject ?property <http://www.softlang.org/ontologies/ce#DataConcept> .
  <http://www.softlang.org/ontologies/ce#DataConcept> ?property ?object .

  ?subject ?subjectProperty ?subjectValue .

  ?object ?objectProperty ?objectValue .
}
WHERE {
  {
    ?subject ?property <http://www.softlang.org/ontologies/ce#DataConcept> .
    ?subject ?subjectProperty ?subjectValue .
  }
  UNION
  {
    <http://www.softlang.org/ontologies/ce#DataConcept> ?property ?object .
    ?object ?objectProperty ?objectValue .
  }
}